[package]
name = "slowpoke_ratatui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui =  "0.28.1"
lyon_tessellation = "1.0.15"
slowpoke = { path = "../slowpoke" }
clamp_to = "0.2.2"
crossterm = "0.28.1"

[lints.clippy]
all = "warn"
