[package]
name = "slowpoke"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.7.2"
either = "1.10.0"
lyon_tessellation = "1.0.13"
clamp_to = "0.2.2"

[dev-dependencies]
rand = "0.9.1"


[lints.clippy]
all = "warn"
# pedantic = "warn"
# nursery = "warn"
